### ISSUE TITLE
葱哥你好 我15年买了你BYMT主题现在突然发现跟你失联了  你的联系方式能告知下吗  邮箱也行！

### ISSUE THREAD

**Issue by umbrellax** [maicong/doutuime#11]
葱哥你好 我15年买了你BYMT主题现在突然发现跟你失联了  你的联系方式能告知下吗  邮箱也行！

**Comment by maicong** [comment]
https://github.com/maicong/BYMT/tree/v3

**Comment by umbrellax** [comment]
葱哥 你这个主题我用到了现在😒
之前域名gkroot.com现在改成nobb.cc
近两年没怎么打理blog，这几天重新搞了下，发现几个bug，能修复下吗
一是主题最高只支持到wp5.0版本，再高版本的话，评论点击回复他人就加载不出来评论回复界面了，
二是bymt-core.js里面好多该更新了
例如
/* SmoothScroll for websites v1.3.8 https://github.com/maicong/OpenAPI/tree/master/SmoothScroll */

这个不支持Passive event listeners
在chrome里滚蛋会报错
三是评论邮件通知 ，bymt3好像没有开启smtp，我通过插件或者在function里插入smtp代码后可以发送邮件，但是存在“我给访客回复时没有邮件通知，他们给我回复就有”的问题以及其他未发现的bug


http://nobb.cc/2022-05-03-2900.html














send&nbsp;from&nbsp;Jonty

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月5日(周四) 上午9:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [maicong/doutuime] 葱哥你好 我15年买了你BYMT主题现在突然发现跟你失联了  你的联系方式能告知下吗  邮箱也行！ (Issue #11)




 
https://github.com/maicong/BYMT/tree/v3

**Comment by umbrellax** [comment]
![Uploading mmexport1651717534755.png…]()

**Comment by maicong** [comment]
抱歉，这个项目目前不再维护了，你可以换别的试试。
